[application]

# App (Project) Name
name = "Writing Tool"



# Dioxus App Default Platform
# desktop, web
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Writing Tool"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.rayburncode"
publisher = "rayburncode"
copyright = "Copyright 2025 rayburncode"
category = "Utility"
short_description = "A utility application built with Dioxus"
long_description = "This application provides various utility functions..."

icon = [
    "icons/icon.icns",
    "icons/icon.ico"
]

