[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
sqlx = "0.8.6"
serde_json = "1.0.140"
reqwest = { version = "0.12.19", features = ["json"] }